# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simple_time_select}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anthony Amoyal"]
  s.date = %q{2009-08-10}
  s.description = %q{A time select component using only ONE select field}
  s.email = %q{tonyamoyal@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "CHANGELOG",
     "MIT_LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "about.yml",
     "init.rb",
     "lib/simple_time_select.rb",
     "pkg/simple_time_select-0.0.0.gem",
     "simple_time_select.gemspec",
     "test/simple_time_select_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/rsturim/simple_time_select}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{This simple plugin gives you that component and allows you to set minute intervals}
  s.test_files = [
    "test/simple_time_select_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
